server:
  port: 9000
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: zuul9000.com
    prefer-ip-address: true

zuul:
  routes:
    myclient.id: alexclient
    myclient.path: /myclient/**
  ignored-services: alexclient
  # not allow visitor to visit the real service address